/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RenewRouteImport } from './routes/renew'
import { Route as WifiRouteImport } from './routes/wifi'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHotspotUsersRouteImport } from './routes/_authenticated/hotspot-users'
import { Route as AuthenticatedMessagingRouteImport } from './routes/_authenticated/messaging'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPppoePlansRouteImport } from './routes/_authenticated/pppoe-plans'
import { Route as AuthenticatedPppoeSessionsRouteImport } from './routes/_authenticated/pppoe-sessions'
import { Route as AuthenticatedPppoeSubscribersRouteImport } from './routes/_authenticated/pppoe-subscribers'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedStaticIpsRouteImport } from './routes/_authenticated/static-ips'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedRoutersIndexRouteImport } from './routes/_authenticated/routers.index'
import { Route as AuthenticatedRoutersRouterIdRouteImport } from './routes/_authenticated/routers.$routerId'
import { Route as AuthenticatedRoutersNewRouteImport } from './routes/_authenticated/routers.new'
import { Route as AuthenticatedVouchersIndexRouteImport } from './routes/_authenticated/vouchers.index'
import { Route as AuthenticatedVouchersBatchIdRouteImport } from './routes/_authenticated/vouchers.$batchId'
import { Route as ApiPublicAgentBackupRouteImport } from './routes/api/public/agent/backup'
import { Route as ApiPublicAgentCommandResultRouteImport } from './routes/api/public/agent/command-result'
import { Route as ApiPublicAgentCommandsRouteImport } from './routes/api/public/agent/commands'
import { Route as ApiPublicAgentHeartbeatRouteImport } from './routes/api/public/agent/heartbeat'
import { Route as ApiPublicAgentMetricsRouteImport } from './routes/api/public/agent/metrics'
import { Route as ApiPublicAgentRegisterRouteImport } from './routes/api/public/agent/register'
import { Route as ApiPublicHooksOfflineSweepRouteImport } from './routes/api/public/hooks/offline-sweep'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewRoute = RenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const WifiRoute = WifiRouteImport.update({
  id: '/wifi',
  path: '/wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHotspotUsersRoute =
  AuthenticatedHotspotUsersRouteImport.update({
    id: '/hotspot-users',
    path: '/hotspot-users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagingRoute = AuthenticatedMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPppoePlansRoute = AuthenticatedPppoePlansRouteImport.update({
  id: '/pppoe-plans',
  path: '/pppoe-plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPppoeSessionsRoute =
  AuthenticatedPppoeSessionsRouteImport.update({
    id: '/pppoe-sessions',
    path: '/pppoe-sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPppoeSubscribersRoute =
  AuthenticatedPppoeSubscribersRouteImport.update({
    id: '/pppoe-subscribers',
    path: '/pppoe-subscribers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaticIpsRoute = AuthenticatedStaticIpsRouteImport.update({
  id: '/static-ips',
  path: '/static-ips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoutersIndexRoute =
  AuthenticatedRoutersIndexRouteImport.update({
    id: '/routers/',
    path: '/routers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoutersRouterIdRoute =
  AuthenticatedRoutersRouterIdRouteImport.update({
    id: '/routers/$routerId',
    path: '/routers/$routerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoutersNewRoute = AuthenticatedRoutersNewRouteImport.update({
  id: '/routers/new',
  path: '/routers/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVouchersIndexRoute =
  AuthenticatedVouchersIndexRouteImport.update({
    id: '/vouchers/',
    path: '/vouchers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVouchersBatchIdRoute =
  AuthenticatedVouchersBatchIdRouteImport.update({
    id: '/vouchers/$batchId',
    path: '/vouchers/$batchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAgentBackupRoute = ApiPublicAgentBackupRouteImport.update({
  id: '/api/public/agent/backup',
  path: '/api/public/agent/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCommandResultRoute =
  ApiPublicAgentCommandResultRouteImport.update({
    id: '/api/public/agent/command-result',
    path: '/api/public/agent/command-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentCommandsRoute = ApiPublicAgentCommandsRouteImport.update({
  id: '/api/public/agent/commands',
  path: '/api/public/agent/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentHeartbeatRoute = ApiPublicAgentHeartbeatRouteImport.update({
  id: '/api/public/agent/heartbeat',
  path: '/api/public/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentMetricsRoute = ApiPublicAgentMetricsRouteImport.update({
  id: '/api/public/agent/metrics',
  path: '/api/public/agent/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRegisterRoute = ApiPublicAgentRegisterRouteImport.update({
  id: '/api/public/agent/register',
  path: '/api/public/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksOfflineSweepRoute =
  ApiPublicHooksOfflineSweepRouteImport.update({
    id: '/api/public/hooks/offline-sweep',
    path: '/api/public/hooks/offline-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/renew': typeof RenewRoute
  '/wifi': typeof WifiRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hotspot-users': typeof AuthenticatedHotspotUsersRoute
  '/messaging': typeof AuthenticatedMessagingRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/pppoe-plans': typeof AuthenticatedPppoePlansRoute
  '/pppoe-sessions': typeof AuthenticatedPppoeSessionsRoute
  '/pppoe-subscribers': typeof AuthenticatedPppoeSubscribersRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/static-ips': typeof AuthenticatedStaticIpsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/routers/$routerId': typeof AuthenticatedRoutersRouterIdRoute
  '/routers/new': typeof AuthenticatedRoutersNewRoute
  '/vouchers/$batchId': typeof AuthenticatedVouchersBatchIdRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/routers/': typeof AuthenticatedRoutersIndexRoute
  '/vouchers/': typeof AuthenticatedVouchersIndexRoute
  '/api/public/agent/backup': typeof ApiPublicAgentBackupRoute
  '/api/public/agent/command-result': typeof ApiPublicAgentCommandResultRoute
  '/api/public/agent/commands': typeof ApiPublicAgentCommandsRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/metrics': typeof ApiPublicAgentMetricsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/hooks/offline-sweep': typeof ApiPublicHooksOfflineSweepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/renew': typeof RenewRoute
  '/wifi': typeof WifiRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hotspot-users': typeof AuthenticatedHotspotUsersRoute
  '/messaging': typeof AuthenticatedMessagingRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/pppoe-plans': typeof AuthenticatedPppoePlansRoute
  '/pppoe-sessions': typeof AuthenticatedPppoeSessionsRoute
  '/pppoe-subscribers': typeof AuthenticatedPppoeSubscribersRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/static-ips': typeof AuthenticatedStaticIpsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/routers/$routerId': typeof AuthenticatedRoutersRouterIdRoute
  '/routers/new': typeof AuthenticatedRoutersNewRoute
  '/vouchers/$batchId': typeof AuthenticatedVouchersBatchIdRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/routers': typeof AuthenticatedRoutersIndexRoute
  '/vouchers': typeof AuthenticatedVouchersIndexRoute
  '/api/public/agent/backup': typeof ApiPublicAgentBackupRoute
  '/api/public/agent/command-result': typeof ApiPublicAgentCommandResultRoute
  '/api/public/agent/commands': typeof ApiPublicAgentCommandsRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/metrics': typeof ApiPublicAgentMetricsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/hooks/offline-sweep': typeof ApiPublicHooksOfflineSweepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/renew': typeof RenewRoute
  '/wifi': typeof WifiRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hotspot-users': typeof AuthenticatedHotspotUsersRoute
  '/_authenticated/messaging': typeof AuthenticatedMessagingRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/pppoe-plans': typeof AuthenticatedPppoePlansRoute
  '/_authenticated/pppoe-sessions': typeof AuthenticatedPppoeSessionsRoute
  '/_authenticated/pppoe-subscribers': typeof AuthenticatedPppoeSubscribersRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/static-ips': typeof AuthenticatedStaticIpsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/routers/$routerId': typeof AuthenticatedRoutersRouterIdRoute
  '/_authenticated/routers/new': typeof AuthenticatedRoutersNewRoute
  '/_authenticated/vouchers/$batchId': typeof AuthenticatedVouchersBatchIdRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/routers/': typeof AuthenticatedRoutersIndexRoute
  '/_authenticated/vouchers/': typeof AuthenticatedVouchersIndexRoute
  '/api/public/agent/backup': typeof ApiPublicAgentBackupRoute
  '/api/public/agent/command-result': typeof ApiPublicAgentCommandResultRoute
  '/api/public/agent/commands': typeof ApiPublicAgentCommandsRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/metrics': typeof ApiPublicAgentMetricsRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/hooks/offline-sweep': typeof ApiPublicHooksOfflineSweepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/renew'
    | '/wifi'
    | '/agents'
    | '/alerts'
    | '/dashboard'
    | '/hotspot-users'
    | '/messaging'
    | '/packages'
    | '/payments'
    | '/portal'
    | '/pppoe-plans'
    | '/pppoe-sessions'
    | '/pppoe-subscribers'
    | '/sites'
    | '/static-ips'
    | '/tickets'
    | '/customers/$customerId'
    | '/routers/$routerId'
    | '/routers/new'
    | '/vouchers/$batchId'
    | '/customers/'
    | '/routers/'
    | '/vouchers/'
    | '/api/public/agent/backup'
    | '/api/public/agent/command-result'
    | '/api/public/agent/commands'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/metrics'
    | '/api/public/agent/register'
    | '/api/public/hooks/offline-sweep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/renew'
    | '/wifi'
    | '/agents'
    | '/alerts'
    | '/dashboard'
    | '/hotspot-users'
    | '/messaging'
    | '/packages'
    | '/payments'
    | '/portal'
    | '/pppoe-plans'
    | '/pppoe-sessions'
    | '/pppoe-subscribers'
    | '/sites'
    | '/static-ips'
    | '/tickets'
    | '/customers/$customerId'
    | '/routers/$routerId'
    | '/routers/new'
    | '/vouchers/$batchId'
    | '/customers'
    | '/routers'
    | '/vouchers'
    | '/api/public/agent/backup'
    | '/api/public/agent/command-result'
    | '/api/public/agent/commands'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/metrics'
    | '/api/public/agent/register'
    | '/api/public/hooks/offline-sweep'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/renew'
    | '/wifi'
    | '/_authenticated/agents'
    | '/_authenticated/alerts'
    | '/_authenticated/dashboard'
    | '/_authenticated/hotspot-users'
    | '/_authenticated/messaging'
    | '/_authenticated/packages'
    | '/_authenticated/payments'
    | '/_authenticated/portal'
    | '/_authenticated/pppoe-plans'
    | '/_authenticated/pppoe-sessions'
    | '/_authenticated/pppoe-subscribers'
    | '/_authenticated/sites'
    | '/_authenticated/static-ips'
    | '/_authenticated/tickets'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/routers/$routerId'
    | '/_authenticated/routers/new'
    | '/_authenticated/vouchers/$batchId'
    | '/_authenticated/customers/'
    | '/_authenticated/routers/'
    | '/_authenticated/vouchers/'
    | '/api/public/agent/backup'
    | '/api/public/agent/command-result'
    | '/api/public/agent/commands'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/metrics'
    | '/api/public/agent/register'
    | '/api/public/hooks/offline-sweep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RenewRoute: typeof RenewRoute
  WifiRoute: typeof WifiRoute
  ApiPublicAgentBackupRoute: typeof ApiPublicAgentBackupRoute
  ApiPublicAgentCommandResultRoute: typeof ApiPublicAgentCommandResultRoute
  ApiPublicAgentCommandsRoute: typeof ApiPublicAgentCommandsRoute
  ApiPublicAgentHeartbeatRoute: typeof ApiPublicAgentHeartbeatRoute
  ApiPublicAgentMetricsRoute: typeof ApiPublicAgentMetricsRoute
  ApiPublicAgentRegisterRoute: typeof ApiPublicAgentRegisterRoute
  ApiPublicHooksOfflineSweepRoute: typeof ApiPublicHooksOfflineSweepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew': {
      id: '/renew'
      path: '/renew'
      fullPath: '/renew'
      preLoaderRoute: typeof RenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wifi': {
      id: '/wifi'
      path: '/wifi'
      fullPath: '/wifi'
      preLoaderRoute: typeof WifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotspot-users': {
      id: '/_authenticated/hotspot-users'
      path: '/hotspot-users'
      fullPath: '/hotspot-users'
      preLoaderRoute: typeof AuthenticatedHotspotUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messaging': {
      id: '/_authenticated/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof AuthenticatedMessagingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pppoe-plans': {
      id: '/_authenticated/pppoe-plans'
      path: '/pppoe-plans'
      fullPath: '/pppoe-plans'
      preLoaderRoute: typeof AuthenticatedPppoePlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pppoe-sessions': {
      id: '/_authenticated/pppoe-sessions'
      path: '/pppoe-sessions'
      fullPath: '/pppoe-sessions'
      preLoaderRoute: typeof AuthenticatedPppoeSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pppoe-subscribers': {
      id: '/_authenticated/pppoe-subscribers'
      path: '/pppoe-subscribers'
      fullPath: '/pppoe-subscribers'
      preLoaderRoute: typeof AuthenticatedPppoeSubscribersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/static-ips': {
      id: '/_authenticated/static-ips'
      path: '/static-ips'
      fullPath: '/static-ips'
      preLoaderRoute: typeof AuthenticatedStaticIpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routers/': {
      id: '/_authenticated/routers/'
      path: '/routers'
      fullPath: '/routers/'
      preLoaderRoute: typeof AuthenticatedRoutersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routers/$routerId': {
      id: '/_authenticated/routers/$routerId'
      path: '/routers/$routerId'
      fullPath: '/routers/$routerId'
      preLoaderRoute: typeof AuthenticatedRoutersRouterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routers/new': {
      id: '/_authenticated/routers/new'
      path: '/routers/new'
      fullPath: '/routers/new'
      preLoaderRoute: typeof AuthenticatedRoutersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vouchers/': {
      id: '/_authenticated/vouchers/'
      path: '/vouchers'
      fullPath: '/vouchers/'
      preLoaderRoute: typeof AuthenticatedVouchersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vouchers/$batchId': {
      id: '/_authenticated/vouchers/$batchId'
      path: '/vouchers/$batchId'
      fullPath: '/vouchers/$batchId'
      preLoaderRoute: typeof AuthenticatedVouchersBatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agent/backup': {
      id: '/api/public/agent/backup'
      path: '/api/public/agent/backup'
      fullPath: '/api/public/agent/backup'
      preLoaderRoute: typeof ApiPublicAgentBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/command-result': {
      id: '/api/public/agent/command-result'
      path: '/api/public/agent/command-result'
      fullPath: '/api/public/agent/command-result'
      preLoaderRoute: typeof ApiPublicAgentCommandResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/commands': {
      id: '/api/public/agent/commands'
      path: '/api/public/agent/commands'
      fullPath: '/api/public/agent/commands'
      preLoaderRoute: typeof ApiPublicAgentCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/heartbeat': {
      id: '/api/public/agent/heartbeat'
      path: '/api/public/agent/heartbeat'
      fullPath: '/api/public/agent/heartbeat'
      preLoaderRoute: typeof ApiPublicAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/metrics': {
      id: '/api/public/agent/metrics'
      path: '/api/public/agent/metrics'
      fullPath: '/api/public/agent/metrics'
      preLoaderRoute: typeof ApiPublicAgentMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/register': {
      id: '/api/public/agent/register'
      path: '/api/public/agent/register'
      fullPath: '/api/public/agent/register'
      preLoaderRoute: typeof ApiPublicAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/offline-sweep': {
      id: '/api/public/hooks/offline-sweep'
      path: '/api/public/hooks/offline-sweep'
      fullPath: '/api/public/hooks/offline-sweep'
      preLoaderRoute: typeof ApiPublicHooksOfflineSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHotspotUsersRoute: typeof AuthenticatedHotspotUsersRoute
  AuthenticatedMessagingRoute: typeof AuthenticatedMessagingRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedPppoePlansRoute: typeof AuthenticatedPppoePlansRoute
  AuthenticatedPppoeSessionsRoute: typeof AuthenticatedPppoeSessionsRoute
  AuthenticatedPppoeSubscribersRoute: typeof AuthenticatedPppoeSubscribersRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedStaticIpsRoute: typeof AuthenticatedStaticIpsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedRoutersRouterIdRoute: typeof AuthenticatedRoutersRouterIdRoute
  AuthenticatedRoutersNewRoute: typeof AuthenticatedRoutersNewRoute
  AuthenticatedVouchersBatchIdRoute: typeof AuthenticatedVouchersBatchIdRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedRoutersIndexRoute: typeof AuthenticatedRoutersIndexRoute
  AuthenticatedVouchersIndexRoute: typeof AuthenticatedVouchersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHotspotUsersRoute: AuthenticatedHotspotUsersRoute,
  AuthenticatedMessagingRoute: AuthenticatedMessagingRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedPppoePlansRoute: AuthenticatedPppoePlansRoute,
  AuthenticatedPppoeSessionsRoute: AuthenticatedPppoeSessionsRoute,
  AuthenticatedPppoeSubscribersRoute: AuthenticatedPppoeSubscribersRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedStaticIpsRoute: AuthenticatedStaticIpsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedRoutersRouterIdRoute: AuthenticatedRoutersRouterIdRoute,
  AuthenticatedRoutersNewRoute: AuthenticatedRoutersNewRoute,
  AuthenticatedVouchersBatchIdRoute: AuthenticatedVouchersBatchIdRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedRoutersIndexRoute: AuthenticatedRoutersIndexRoute,
  AuthenticatedVouchersIndexRoute: AuthenticatedVouchersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RenewRoute: RenewRoute,
  WifiRoute: WifiRoute,
  ApiPublicAgentBackupRoute: ApiPublicAgentBackupRoute,
  ApiPublicAgentCommandResultRoute: ApiPublicAgentCommandResultRoute,
  ApiPublicAgentCommandsRoute: ApiPublicAgentCommandsRoute,
  ApiPublicAgentHeartbeatRoute: ApiPublicAgentHeartbeatRoute,
  ApiPublicAgentMetricsRoute: ApiPublicAgentMetricsRoute,
  ApiPublicAgentRegisterRoute: ApiPublicAgentRegisterRoute,
  ApiPublicHooksOfflineSweepRoute: ApiPublicHooksOfflineSweepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
